
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true

  #database-platform: org.hibernate.dialect.PostgreSQLDialect

   ## spring:
     ## jpa:
       ## properties:
         ## hibernate:
           ## format_sql=true:
